//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BirthDay { get; set; }
        public string Gender { get; set; }
        public string ShowMe { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public byte[] Image1 { get; set; }
        public byte[] Image2 { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime CreatedDay { get; set; }
        public bool Active { get; set; }
    }
}
