//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invite
    {
        public int Id { get; set; }
        public int MainID { get; set; }
        public int Second { get; set; }
        public bool Accepted { get; set; }
        public bool IsActive { get; set; }
    }
}
